---
title: "master"
author: "Huy Le Quang"
date: "6/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F)
```

## 1. Set up in R

```{r}

## Set working directory:

setwd ("G:/My Drive/IPSDS/Modern Workflow in Data Science/Assignments/Assignment-2/")
getwd()

## Load necessary packages

library(tidyverse)
library(ggplot2)
library(foreign)
library(pander)

```

## 2. Load data to R

```{r}

data_raw <- read.dta("./ZA7500_v3-0-0.dta/ZA7500_v3-0-0.dta")

```

## 3. Clean and save new dataset

```{r}

# select variables of interest

vars <- c("country", "v72", "v80", "age", "v225", "v243_r")

data_final <- data_raw %>% 
    select(vars) %>% 
    filter(age >=0) %>% 
    filter(v72 == "agree strongly"| v72 == "agree"| 
       v72 == "disagree"| v72 == "disagree strongly") %>% 
    filter(v80 == "agree strongly"|v80 == "agree"|v80 == "neither agree nor disagree"|
           v80 == "disagree"|v80 == "disagree strongly") %>% 
    filter(v225 == "male"|v225 == "female") %>% 
    filter(v243_r == "lower"|v243_r == "medium"|v243_r == "higher") %>% 
    mutate(working_mom = as.numeric(v72),
           immigrant_job = as.numeric(v80),
           education = as.numeric(v243_r),
           male = ifelse(v225 == "male", 1, 0),
           male = factor(male,
                         labels = c("Female", "Male")),
           working_mom_fct = factor(working_mom,
                                    labels = c("agree strongly", "agree", 
                                               "disagree","disagree strongly")),
           immigrant_job_fct = factor(immigrant_job,
                                      labels = c("agree strongly", "agree", "neither agree nor disagree",
                                                 "disagree", "disagree strongly")),
           education_fct = factor(education,
                                  labels = c("lower", "medium", "higher")),
            working_mom = case_when(working_mom == 9 ~ 1,
                                    working_mom == 10 ~ 2,
                                    working_mom == 11 ~ 3,
                                    working_mom == 12 ~ 4),
           immigrant_job = case_when(immigrant_job == 9 ~ 1,
                                     immigrant_job == 10 ~ 2,
                                     immigrant_job == 11 ~ 3,
                                     immigrant_job == 12 ~ 4,
                                     immigrant_job == 13 ~ 5),
           education = case_when(education == 8 ~ 1,
                                 education == 9 ~ 2,
                                 education == 10 ~ 3))
    
          

summary(data_final)

save(data_final, file = "data_final.RData")

# make smaller data for descriptive:

explore_data <- data_final %>% 
    select(-v72, -v80, -v225, -v243_r, -education)

```


```{r}

# Function for batch creation

for (country in unique(explore_data$country)) {
   rmarkdown::render('./batch_reports/country_report.Rmd', 
        params = list(country = country),
        output_file = paste0("Report-", country, ".html"))
}

```
